version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.6.3-jdk-8
    steps:
      - run: echo "start..."
      - run: git clone https://github.com/Pay-Group/best-pay-sdk.git
      - run: mvn clean package -Dmaven.test.skip=true -U